//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_CARD_DEAL_HISTORY = new HashSet<TB_CARD_DEAL_HISTORY>();
            this.TB_GAME_ACCOUNT = new HashSet<TB_GAME_ACCOUNT>();
            this.TB_GAME_PRICE_OFFER = new HashSet<TB_GAME_PRICE_OFFER>();
            this.TB_SELL_DEAL_HISTORY = new HashSet<TB_SELL_DEAL_HISTORY>();
            this.TB_BILL = new HashSet<TB_BILL>();
        }
    

        public string ID { get; set; }

        [Required]
        [StringLength(maximumLength: 20, MinimumLength = 8,ErrorMessage = "Chieu dai toi ta cua {0} la {2} - {1} ki tu}")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage ="Bắt buộc")]
        public string PASSWORD_KEY { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string CURRENT_ADDRESS { get; set; }
        
        public virtual ICollection<TB_CARD_DEAL_HISTORY> TB_CARD_DEAL_HISTORY { get; set; }
        public virtual ICollection<TB_GAME_ACCOUNT> TB_GAME_ACCOUNT { get; set; }
        public virtual ICollection<TB_GAME_PRICE_OFFER> TB_GAME_PRICE_OFFER { get; set; }
        public virtual ICollection<TB_SELL_DEAL_HISTORY> TB_SELL_DEAL_HISTORY { get; set; }
        public virtual TB_MONEY TB_MONEY { get; set; }
        public virtual ICollection<TB_BILL> TB_BILL { get; set; }
    }
}
