//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TB_ADMIN
    {
        public TB_ADMIN()
        {

        }
        public TB_ADMIN(string USERNAME, string PASSWORD_KEY)
        {
            this.USERNAME = USERNAME;
            this.PASSWORD_KEY = PASSWORD_KEY;
        }

        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD_KEY { get; set; }
        public string NAME { get; set; }
    }
}
