//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARD_DEAL_HISTORY
    {
        public string HIS_ID { get; set; }
        public Nullable<System.DateTime> HIS_TIME { get; set; }
        public string COMPANY { get; set; }
        public string CARD_NUMBER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<int> DENOMINATIONS { get; set; }
        public string RESULT { get; set; }
        public string ID { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
    }
}
