//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    public partial class TB_GAME_ACCOUNT_DETAIL
    {
        public string USERNAME { get; set; }

        [Display(Name ="Tướng")]
        [Required(ErrorMessage = "Chưa chọn số lượng tướng")]
        public int GENERAL_NUMBER { get; set; }

        [Display(Name = "Trang phục")]
        [Required(ErrorMessage = "Chưa chọn số lượng trang phục")]
        public int SKIN_NUMBER { get; set; }

        [Display(Name = "Bảng ngọc")]
        [Required(ErrorMessage = "Chưa chọn số lượng bảng ngọc")]
        public int GEM_NUMBER { get; set; }

        [Display(Name = "Level")]
        [Required(ErrorMessage = "Chưa chọn level")]
        public int LEVEL_NUMBER { get; set; }

        [Display(Name = "Bậc cao nhất")]
        [Required(ErrorMessage = "Chưa chọn bậc")]
        public string BEST_RANK { get; set; }

        [Display(Name = "Bậc hiện tại")]
        public string CURRENT_RANK { get; set; }

        [Display(Name = "Clan")]
        public string CLAN_NAME { get; set; }
    
        public virtual TB_GAME_ACCOUNT TB_GAME_ACCOUNT { get; set; }
        public virtual TB_RANK_NAME TB_RANK_NAME { get; set; }
        public virtual TB_RANK_NAME TB_RANK_NAME1 { get; set; }
    }
}
