//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAME_IMAGE
    {
        public string USERNAME { get; set; }
        public string ACCOUNT_IMAGE { get; set; }
        public int ID_IMG { get; set; }
    }
}
