//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAME_ACCOUNT_DETAIL
    {
        public string USERNAME { get; set; }
        public int GENERAL_NUMBER { get; set; }
        public int SKIN_NUMBER { get; set; }
        public int GEM_NUMBER { get; set; }
        public int LEVEL_NUMBER { get; set; }
        public string BEST_RANK { get; set; }
        public string CURRENT_RANK { get; set; }
        public string CLAN_NAME { get; set; }
    
        public virtual TB_RANK_NAME TB_RANK_NAME { get; set; }
        public virtual TB_RANK_NAME TB_RANK_NAME1 { get; set; }
        public virtual TB_GAME_ACCOUNT TB_GAME_ACCOUNT { get; set; }
    }
}
