//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAME_ACCOUNT
    {
        public TB_GAME_ACCOUNT()
        {
            this.TB_BILL = new HashSet<TB_BILL>();
            this.TB_GAME_PRICE_OFFER = new HashSet<TB_GAME_PRICE_OFFER>();
            this.TB_SELL_DEAL_HISTORY = new HashSet<TB_SELL_DEAL_HISTORY>();
        }
    
        public string USERNAME { get; set; }
        public string PASSWORD_KEY { get; set; }
        public Nullable<int> ORIGINAL_PRICE { get; set; }
        public Nullable<int> ACCEPT_PRICE { get; set; }
        public Nullable<int> CURRENT_STATUS { get; set; }
        public string RE_IMAGE { get; set; }
        public string IMG_ID { get; set; }
        public Nullable<System.DateTime> DATE_UPLOAD { get; set; }
        public Nullable<int> ID { get; set; }
        public string USER_ACCOUNT_ID { get; set; }
    
        public virtual ICollection<TB_BILL> TB_BILL { get; set; }
        public virtual TB_GAME_ACCOUNT_DETAIL TB_GAME_ACCOUNT_DETAIL { get; set; }
        public virtual TB_GAME_IMAGE TB_GAME_IMAGE { get; set; }
        public virtual TB_USER TB_USER { get; set; }
        public virtual ICollection<TB_GAME_PRICE_OFFER> TB_GAME_PRICE_OFFER { get; set; }
        public virtual ICollection<TB_SELL_DEAL_HISTORY> TB_SELL_DEAL_HISTORY { get; set; }
    }
}
