//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAME_PRICE_OFFER
    {
        public string USERNAME { get; set; }
        public string USER_ACCOUNT_ID { get; set; }
        public Nullable<decimal> USER_PRICE_OFFER { get; set; }
        public Nullable<byte> CURRENT_STATUS { get; set; }
    
        public virtual TB_USER TB_USER { get; set; }
        public virtual TB_GAME_ACCOUNT TB_GAME_ACCOUNT { get; set; }
    }
}
