//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAME_IMAGE
    {
        public TB_GAME_IMAGE()
        {
            this.TB_GAME_ACCOUNT = new HashSet<TB_GAME_ACCOUNT>();
        }
    
        public string USERNAME { get; set; }
        public string IMG_1 { get; set; }
        public string IMG_2 { get; set; }
        public string IMG_3 { get; set; }
        public string IMG_4 { get; set; }
    
        public virtual ICollection<TB_GAME_ACCOUNT> TB_GAME_ACCOUNT { get; set; }
    }
}
