//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RANK_NAME
    {
        public TB_RANK_NAME()
        {
            this.TB_GAME_ACCOUNT_DETAIL = new HashSet<TB_GAME_ACCOUNT_DETAIL>();
            this.TB_GAME_ACCOUNT_DETAIL1 = new HashSet<TB_GAME_ACCOUNT_DETAIL>();
        }
    
        public string RANK_ID { get; set; }
        public string RANK_NAME { get; set; }
    
        public virtual ICollection<TB_GAME_ACCOUNT_DETAIL> TB_GAME_ACCOUNT_DETAIL { get; set; }
        public virtual ICollection<TB_GAME_ACCOUNT_DETAIL> TB_GAME_ACCOUNT_DETAIL1 { get; set; }
    }
}
