//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_CARD_DEAL_HISTORY = new HashSet<TB_CARD_DEAL_HISTORY>();
            this.TB_GAME_PRICE_OFFER = new HashSet<TB_GAME_PRICE_OFFER>();
            this.TB_SELL_DEAL_HISTORY = new HashSet<TB_SELL_DEAL_HISTORY>();
        }
         
        public string ID { get; set; }
        [Display(Name ="Tên đăng nhập")]
        [Required(ErrorMessage = "Chưa nhập tên đăng nhập")]  
        public string USERNAME { get; set; }
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Chưa nhập mật khẩu")]  
        public string PASSWORD_KEY { get; set; }
        [Required(ErrorMessage = "Chưa nhập họ tên")]  
        public string NAME { get; set; }
        [Required(ErrorMessage = "Chưa nhập email")]  
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]  
        public string PHONE { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]  
        public string CURRENT_ADDRESS { get; set; }
    
        public virtual ICollection<TB_CARD_DEAL_HISTORY> TB_CARD_DEAL_HISTORY { get; set; }
        public virtual ICollection<TB_GAME_PRICE_OFFER> TB_GAME_PRICE_OFFER { get; set; }
        public virtual ICollection<TB_SELL_DEAL_HISTORY> TB_SELL_DEAL_HISTORY { get; set; }
    }
}
