﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeCareWithYourFuckingCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_CARD_DEAL_HISTORY = new HashSet<TB_CARD_DEAL_HISTORY>();
            this.TB_GAME_PRICE_OFFER = new HashSet<TB_GAME_PRICE_OFFER>();
            this.TB_SELL_DEAL_HISTORY = new HashSet<TB_SELL_DEAL_HISTORY>();
        }

        public string ID { get; set; }

        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "Chưa nhập tên đăng nhập")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "{0} phải có độ dài từ {2} đến {1} kí tự")]
        public string USERNAME { get; set; }

        [Display(Name = "Mật khẩu")]
        [StringLength(40, MinimumLength = 8, ErrorMessage = "{0} phải có độ dài từ {2} đến {1} kí tự")]
        [Required(ErrorMessage = "Chưa nhập mật khẩu")]
        public string PASSWORD_KEY { get; set; }

        [System.ComponentModel.DataAnnotations.Compare("PASSWORD_KEY", ErrorMessage = "Mật khẩu không trùng khớp")]
        [Required(ErrorMessage = "Chưa xác nhận lại mật khẩu")]
        public string ConfirmPassWord { get; set; }

        [StringLength(30, MinimumLength = 2, ErrorMessage = "{0} phải có độ dài từ {2} đến {1} kí tự")]
        [Required(ErrorMessage = "Chưa nhập họ tên")]
        [Display(Name = "Họ tên")]
        public string NAME { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        [Required(ErrorMessage = "Chưa nhập email")]
        public string EMAIL { get; set; }

        [Display(Name = "Số điện thoại")]
        [StringLength(10)]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ")]
        [Required(ErrorMessage = "Chưa nhập số điện thoại")]
        public string PHONE { get; set; }

        [Display(Name = "Địa chỉ hiện tại")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "{0} phải có độ dài từ {2} đến {1} kí tự")]
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        public string CURRENT_ADDRESS { get; set; }

        public virtual ICollection<TB_CARD_DEAL_HISTORY> TB_CARD_DEAL_HISTORY { get; set; }
        public virtual ICollection<TB_GAME_PRICE_OFFER> TB_GAME_PRICE_OFFER { get; set; }
        public virtual ICollection<TB_SELL_DEAL_HISTORY> TB_SELL_DEAL_HISTORY { get; set; }
    }
}
